---
# file: deploy_template_from_is.yml

## FEDORA VMs CANNOT BE CUSTOMIZED BY VCENTER
## THUS WE NEED TO CONFIGURE THEM IN PLACE

- hosts: fxhtyul2pdkr003.fxhosting.net
  gather_facts: no
  become: no
  roles:
          - vmware-fedora36_vm_from_iso


