- hosts: fxhtyul2pnet001.fxhosting.net
  tasks:
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        msg: System {{ inventory_hostname }} is {{ ansible_os_family }}
    - include: ../mdatp/onboarding_setup.yml
    - include: ../mdatp/add_yum_repo.yml
#    - name: Install MDATP
#      dnf:
#        name: mdatp
#        state: latest
#        enablerepo: packages-microsoft-[channel]
    - name: Install MDATP (RedHat family OS)
      dnf:
        name: mdatp
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"
    - name: Install MDATP (Debian family OS)
      apt:
        name: mdatp
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"
